ci: Delete "Download maven dependencies" task in "Test" workflow
Causes an error when changed version in pom.xml.
---
Error:  Failed to execute goal on project server: Could not resolve dependencies for project dev.medzik.librepass:server:jar:1.3.0: The following artifacts could not be resolved: dev.medzik.librepass:shared:jar:1.3.0 (absent): Could not find artifact dev.medzik.librepass:shared:jar:1.3.0 in central (https://repo.maven.apache.org/maven2) -> [Help 1]
---
It seems to download submodules from maven central, which it should not do.